#include <stdio.h>
#include <stdint.h>

#define MAX_MSG_BUFFER 500 // Define the physical limit of your array
#ifndef GERMAN_KEYBOARDCODES_H
#define GERMAN_KEYBOARDCODES_H

#define GERMAN_KEYBOARD_SC_A                                 0x04
#define GERMAN_KEYBOARD_SC_B                                 0x05
#define GERMAN_KEYBOARD_SC_C                                 0x06
#define GERMAN_KEYBOARD_SC_D                                 0x07
#define GERMAN_KEYBOARD_SC_E                                 0x08
#define GERMAN_KEYBOARD_SC_F                                 0x09
#define GERMAN_KEYBOARD_SC_G                                 0x0A
#define GERMAN_KEYBOARD_SC_H                                 0x0B
#define GERMAN_KEYBOARD_SC_I                                 0x0C
#define GERMAN_KEYBOARD_SC_J                                 0x0D
#define GERMAN_KEYBOARD_SC_K                                 0x0E
#define GERMAN_KEYBOARD_SC_L                                 0x0F
#define GERMAN_KEYBOARD_SC_M                                 0x10
#define GERMAN_KEYBOARD_SC_N                                 0x11
#define GERMAN_KEYBOARD_SC_O                                 0x12
#define GERMAN_KEYBOARD_SC_P                                 0x13
#define GERMAN_KEYBOARD_SC_Q                                 0x14
#define GERMAN_KEYBOARD_SC_R                                 0x15
#define GERMAN_KEYBOARD_SC_S                                 0x16
#define GERMAN_KEYBOARD_SC_T                                 0x17
#define GERMAN_KEYBOARD_SC_U                                 0x18
#define GERMAN_KEYBOARD_SC_V                                 0x19
#define GERMAN_KEYBOARD_SC_W                                 0x1A
#define GERMAN_KEYBOARD_SC_X                                 0x1B
#define GERMAN_KEYBOARD_SC_Y                                 0x1D
#define GERMAN_KEYBOARD_SC_Z                                 0x1C
#define GERMAN_KEYBOARD_SC_1_AND_EXCLAMATION                 0x1E
#define GERMAN_KEYBOARD_SC_2_AND_QUOTES                          0x1F
#define GERMAN_KEYBOARD_SC_3_AND_PARAGRAPH                0x20
#define GERMAN_KEYBOARD_SC_4_AND_DOLLAR                      0x21
#define GERMAN_KEYBOARD_SC_5_AND_PERCENTAGE                  0x22
#define GERMAN_KEYBOARD_SC_6_AND_AMPERSAND                       0x23
#define GERMAN_KEYBOARD_SC_7_AND_SLASH_AND_OPENING_BRACE                   0x24
#define GERMAN_KEYBOARD_SC_8_AND_OPENING_PARENTHESIS_AND_OPENING_BRACKET 0x25
#define GERMAN_KEYBOARD_SC_9_AND_CLOSING_PARENTHESIS_AND_CLOSING_BRACKET 0x26
#define GERMAN_KEYBOARD_SC_0_AND_EQUAL_AND_CLOSING_BRACE         0x27
#define GERMAN_KEYBOARD_SC_SHARP_S_AND_QUESTION_AND_BACKSLASH 0x2D
#define GERMAN_KEYBOARD_SC_CARET_AND_DEGREE 0x35
#define GERMAN_KEYBOARD_SC_PLUS_AND_ASTERISK_AND_TILDE 0x30
#define GERMAN_KEYBOARD_SC_MINUS_AND_UNDERSCORE 0x38
#define GERMAN_KEYBOARD_SC_COMMA_AND_SEMICOLON 0x36
#define GERMAN_KEYBOARD_SC_DOT_AND_COLON 0x37
#define GERMAN_KEYBOARD_SC_ENTER                             0x28
#define GERMAN_KEYBOARD_SC_ESCAPE                            0x29
#define GERMAN_KEYBOARD_SC_BACKSPACE                         0x2A
#define GERMAN_KEYBOARD_SC_TAB                               0x2B
#define GERMAN_KEYBOARD_SC_SPACE                             0x2C
#define GERMAN_KEYBOARD_SC_HASHMARK_AND_APOSTROPHE   0x32
#define GERMAN_KEYBOARD_SC_LESS_THAN_AND_GREATER_THAN_AND_PIPE 0x64

#endif //GERMAN_KEYBOARDCODES_H



uint8_t msg[MAX_MSG_BUFFER] = {
    GERMAN_KEYBOARD_SC_A,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_B,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_C,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_D,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_E,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_F,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_G,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_H,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_I,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_J,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_K,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_L,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_M,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_N,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_O,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_P,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_Q,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_R,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_S,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_T,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_U,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_V,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_W,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_X,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_Y,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_Z,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_A,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_B,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_C,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_D,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_E,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_F,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_G,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_H,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_I,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_J,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_K,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_L,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_M,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_N,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_O,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_P,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_Q,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_R,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_S,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_T,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_U,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_V,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_W,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_X,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_Y,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_Z,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_1_AND_EXCLAMATION,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_2_AND_QUOTES,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_3_AND_PARAGRAPH,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_4_AND_DOLLAR,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_5_AND_PERCENTAGE,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_6_AND_AMPERSAND,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_7_AND_SLASH_AND_OPENING_BRACE,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_8_AND_OPENING_PARENTHESIS_AND_OPENING_BRACKET,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_9_AND_CLOSING_PARENTHESIS_AND_CLOSING_BRACKET,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_0_AND_EQUAL_AND_CLOSING_BRACE,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_1_AND_EXCLAMATION, // !
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_8_AND_OPENING_PARENTHESIS_AND_OPENING_BRACKET, // (
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_9_AND_CLOSING_PARENTHESIS_AND_CLOSING_BRACKET, // )
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_MINUS_AND_UNDERSCORE, // -
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_MINUS_AND_UNDERSCORE, // _
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_PLUS_AND_ASTERISK_AND_TILDE, // +
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_0_AND_EQUAL_AND_CLOSING_BRACE, // =
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_PLUS_AND_ASTERISK_AND_TILDE, // ~
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_COMMA_AND_SEMICOLON, // ;
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_DOT_AND_COLON, // :
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_COMMA_AND_SEMICOLON, // ,
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_DOT_AND_COLON, // .
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_LESS_THAN_AND_GREATER_THAN_AND_PIPE, // <
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_LESS_THAN_AND_GREATER_THAN_AND_PIPE, // >
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_8_AND_OPENING_PARENTHESIS_AND_OPENING_BRACKET, // [
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_9_AND_CLOSING_PARENTHESIS_AND_CLOSING_BRACKET, // ]
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_7_AND_SLASH_AND_OPENING_BRACE, // {
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_0_AND_EQUAL_AND_CLOSING_BRACE, // }
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_7_AND_SLASH_AND_OPENING_BRACE, // /
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_SHARP_S_AND_QUESTION_AND_BACKSLASH, // ?
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_6_AND_AMPERSAND, // &
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_4_AND_DOLLAR, // $
    GERMAN_KEYBOARD_SC_ENTER,
    GERMAN_KEYBOARD_SC_SPACE,
    GERMAN_KEYBOARD_SC_ENTER
};
int a = 0;
volatile uint8_t global_index = 0; // Reset this to 0 to start typing
uint8_t global_string_len = 168;


void insert(uint8_t arr[], uint8_t *n, int pos, uint8_t val) {
    // 1. Check for Overflow: If current size is already at capacity, stop.
    if (*n >= MAX_MSG_BUFFER) {
        return; 
    }

    // 2. Bound Check: Ensure the insertion position is valid
    if (pos > *n) {
        pos = *n;
    }

    // 3. Shift elements to the right
    // We start from the current end (*n) and move backwards to 'pos'
    for (int i = *n; i > pos; i--) {
        arr[i] = arr[i - 1];
    }

    // 4. Insert the value at the now-empty position
    arr[pos] = val;

    // 5. Increase the tracked length
    (*n)++;
}

uint8_t msg[MAX_MSG_BUFFER] = {1, 2, 3, 4, 5};

int main() {
    uint8_t n = 5; // Current size of the array
    int pos = 2;  // Position to insert the new value
    uint8_t val = 99; // Value to insert


    int i = 0;
    uint8_t srlenght = 0;
    while (1){
        global_string_len = 168;


    if (i == 100) {
        insert(msg, &global_string_len, 0, 4);
		 	global_index = 0; // Reset index to start typing from the beginning
        i = 0;

        printf("\n Array after insertion: ");
        for (int i = 0; i < global_string_len; i++) {
            printf("%d ", msg[i]);
    
        }
    
    } else {
        i++;
    }




}
}